### ISSUE TITLE
Installation problems (makefile error after install.sh)

### ISSUE THREAD

**Issue by gitgitgat** [ossec/ossec-hids#1790]
Title says it. The error output: 

> Running the Makefile
> cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -c external/cJSON/cJSON.c -o external/cJSON/cJSON.o
> ar -crs libcJSON.a external/cJSON/cJSON.o
> ranlib libcJSON.a
> cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLOCAL -Wall -Wextra -I./ -I./headers/ -DARGV0=\"ossec-maild\" -c os_maild/maild.c -o os_maild/maild.o
> In file included from ./headers/shared.h:215:0,
>                  from os_maild/maild.c:10:
> ./os_regex/os_regex.h:19:10: fatal error: pcre2.h: No such file or directory
>  #include <pcre2.h>
>           ^~~~~~~~~
> compilation terminated.
> Makefile:926: recipe for target 'os_maild/maild.o' failed
> make: *** [os_maild/maild.o] Error 1
> 
>  Error 0x5.
>  Building error. Unable to finish the installation.

have so far only tried using different versions, deleting/removing and re-installing.

**Comment by gitgitgat** [comment]
It only happens with manual installation, apt-get install works with ubuntu 18.04

**Comment by ddpbsd** [comment]
Looks like the pcre2 dev package isn’t installed

**Comment by gitgitgat** [comment]
that is weird, I have the package installed in ossec-hids/src/external/

**Comment by ddpbsd** [comment]
Then PCRE2_SYSTEM needs to be set to no

**Comment by gitgitgat** [comment]
that worked but then I encountered:

> In file included from ./external/compat/imsg.c:21:0:
> ./external/compat/includes.h:65:10: fatal error: openssl/opensslv.h: No such file or directory
>  #include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> In file included from ./external/compat/imsg-buffer.c:21:0:
> ./external/compat/includes.h:65:10: fatal error: openssl/opensslv.h: No such file or directory
>  #include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
>           ^~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> Makefile:929: recipe for target 'ossec-maild' failed
> make: *** [ossec-maild] Error 1
> 
>  Error 0x5.
>  Building error. Unable to finish the installation.

**Comment by gitgitgat** [comment]
openssl is up to date

**Comment by ddpbsd** [comment]
Is the dev or devel package installed? I haven’t had any problems on Ubuntu, but I’m not positive I’ve tried 18.04

**Comment by gitgitgat** [comment]
ok, it was just the missing libssl-dev package. Thanks.

**Comment by CalfCrusher** [comment]
I have same problem  but installing libssl-dev NOT solve the problem. I cant' compile it

error is:

```
In file included from ./headers/shared.h:215:0,
                 from os_maild/maild.c:10:
./os_regex/os_regex.h:19:10: fatal error: pcre2.h: File o directory non esistente
 #include <pcre2.h>
          ^~~~~~~~~
compilation terminated.
Makefile:926: recipe for target 'os_maild/maild.o' failed
make: *** [os_maild/maild.o] Error 1
```

**Comment by ddpbsd** [comment]
@CalfCrusher Install the pcre2-dev package.

**Comment by y0sua** [comment]
```
5- Installing the system
 - Running the Makefile
cc -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DHAVE_SYSTEMD -DZLIB_SYSTEM -DUSE_PCRE2_JIT -Wall -Wextra -I./ -I./headers/ os_maild/config.o os_maild/mail_list.o os_maild/maild.o os_maild/os_maild_client.o os_maild/sendcustomemail.o os_maild/sendmail.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a  -lm -lpthread -lsystemd -lpcre2-8 -lz  ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
In file included from ./external/compat/imsg.c:21:
./external/compat/includes.h:65:10: fatal error: openssl/opensslv.h: No such file or directory
   65 | #include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
In file included from ./external/compat/imsg-buffer.c:21:
./external/compat/includes.h:65:10: fatal error: openssl/opensslv.h: No such file or directory
   65 | #include <openssl/opensslv.h> /* For OPENSSL_VERSION_NUMBER */
      |          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:930: ossec-maild] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.
```

Hello guys, I got this error, can you help me, please?

Thanks

**Comment by shubham2662** [comment]
cc -fPIC -nopie -I./external/compat -DMAX_AGENTS=2048 -DOSSECHIDS -DDEFAULTDIR=\"/var/ossec\" -DUSER=\"ossec\" -DREMUSER=\"ossecr\" -DGROUPGLOBAL=\"ossec\" -DMAILUSER=\"ossecm\" -DLinux -DINOTIFY_ENABLED -DHAVE_SYSTEMD -DZLIB_SYSTEM -DUSE_PCRE2_JIT -DLIBOPENSSL_ENABLED -Wall -Wextra -I./ -I./headers/ os_maild/maild.o os_maild/sendmail.o os_maild/sendcustomemail.o os_maild/config.o os_maild/os_maild_client.o os_maild/mail_list.o os_crypto.a config.a shared.a os_net.a os_regex.a os_xml.a  -lm -lpthread -lsystemd -lpcre2-8 -lssl -lcrypto -lz  ./external/compat/imsg.c ./external/compat/imsg-buffer.c -o ossec-maild
cc: error: unrecognized command line option ‘-nopie’; did you mean ‘-no-pie’?
make: *** [Makefile:930: ossec-maild] Error 1

 Error 0x5.
 Building error. Unable to finish the installation.

root@debian:/home/shuhari/ossec-hids-3.7.0# makefile
bash: makefile: command not found
root@debian:/home/shuhari/ossec-hids-3.7.0# make clean -nopie
make: *** No rule to make target 'clean'.  Stop.
root@debian:/home/shuhari/ossec-hids-3.7.0# cc --version
cc (Debian 8.3.0-6) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.



_____________________________________
 Still having the same issue  while installing the server on Debian  ...
if anyone knows pls ping me 
version : ossec 3.7.0

**Comment by mmljmb3** [comment]
So I figured out what needs to be done to install this on Debian (ARM64). 
install all these:
apt install libz-dev libssl-dev libpcre2-dev libevent-dev build-essential libsystemd-dev
unpack the ossec-hids-master.zip
inside the unpacked folder you need run chmod 755 /analysisd/compiled_rules/register_rule.sh 
inside the unpacked folder you need run  chmod 755 /src/init/*.sh
go back to the  ossec-hids-master and run ./install.sh and it should install without issue. 

I also got OUM to install on Debian ARM64 (Raspberry PI)
