### ISSUE TITLE
Build fails with GCC-10 and GCC-9 when -fno-common option is used

### ISSUE THREAD

**Issue by rseichter** [ossec/ossec-hids#1871]
GCC version 10 will soon arrive, and one of the planned changes is switching from `-fcommon` (default in GCC 9) to the new default `-fno-common`.

As documented in Gentoo Linux [issue 720088](https://bugs.gentoo.org/720088), building OSSEC 3.6.0 fails with typical linker errors when `-fno-common` is used:

```
/usr/lib/gcc/x86_64-pc-linux-gnu/9.3.0/../../../../x86_64-pc-linux-gnu/bin/ld: os_net.a(os_net.o):
(.bss+0x0): multiple definition of `agt'; client-agent/config.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:1016: ossec-agentd] Error 1
```

We have a Gentoo [Wiki article](https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common) describing the problem in more detail. While patching as a temporary measure is possible (I am involved in my role as the designated Gentoo package maintainer), the OSSEC source code needs to be fixed.

**Comment by ddpbsd** [comment]
Thanks for reporting this. I've got some initial fixes in a branch, but want to test them a bit before opening a PR.

**Comment by ddpbsd** [comment]
Submitted pull request #1875 
More testing is always appreciated.

**Comment by rseichter** [comment]
@ddpbsd Works for me. I have submitted a Gentoo ebuild pull request containing your changes as a combined patch. Thank you for addressing this bug.

**Comment by rseichter** [comment]
@ddpbsd While the agent build now works with `-fno-common`, server and hybrid builds still fail. I had hoped your changes relate to all build types?

**Comment by ddpbsd** [comment]
@rseichter That was a silly omission on my part. I'll work on those today.

**Comment by ddpbsd** [comment]
Actually, I'm not triggering any failures for the server build using gcc 7.5.0. Are there logs of the gentoo builds publicly available?

**Comment by rseichter** [comment]
I have just made a [server build log](https://seichter.de/tmp/ossec/server.log) available for you, generated by GCC 9.3.0.

**Comment by ddpbsd** [comment]
Thanks! I'll start looking into it.

**Comment by ddpbsd** [comment]
The pull request was updated. Hopefully I managed to test all of the things that need testing.

**Comment by rseichter** [comment]
Thanks for the update, Dan. I have just successfully completed three different builds (agent, hybrid and server). Looks good to me.
